### ISSUE TITLE
Mise à jour impossible de 4.0.0~ynh1 à 4.0.0~ynh2

### ISSUE THREAD

**Issue by makotoworkshop** [YunoHost-Apps/spip_ynh#36]
### Describe the bug

Mise à jour impossible, une erreur python bloque l'opération : `de 4.0.0~ynh1 à 4.0.0~ynh2`

### Context

- Hardware: *PC Linux 4.19.0-17-amd64 Debian 4.19.194-3 (2021-07-18) x86_64 GNU/Linux*
- YunoHost version: YunoHost 4.2.8.3 (stable)
- I have access to my server: *Through SSH | through the webadmin | direct access via keyboard / screen | ...*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- If upgrading, current package version: *can be found in the admin, or with `yunohost app info $app_id`* 
`SPIP (spip) de 4.0.0~ynh1 à 4.0.0~ynh2`

### Steps to reproduce

- *If you performed a command from the CLI, the command itself is enough. For example:*
    ```sh
    yunohost app upgrade spip
    ```
    Ou bien 
    ```sh
    yunohost app upgrade spip -u https://github.com/YunoHost-Apps/spip_ynh
   ```
### Logs

https://paste.yunohost.org/raw/evoriqijop

```Info : Mise à jour de spip...
Info : [+...................] > Loading installation settings...
Info : [#+..................] > Checking version...
Info : [##++................] > Backing up the app before upgrading (may take a while)...
Info : [####+...............] > Ensuring downward compatibility...
Info : [#####+..............] > Making sure dedicated system user exists...
Info : [######++............] > Upgrading NGINX web server configuration...
Info : [########+...........] > Upgrading PHP-FPM configuration...
Info : [#########+..........] > Setuping application with CURL...
Info : [##########++........] > Configuring SSOwat...
Attention : File /var/www/spip/config/connect.php has been manually modified since the installation or last upgrade. So it has been duplicated in /home/yunohost.conf/backup//var/www/spip/config/connect.php.backup.20210915.114622
Info : [############+.......] > Finalizing installation...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3/dist-packages/moulinette/utils/process.py", line 121, in run
    for line in iter(self.pipeReader.readline, ""):
  File "/usr/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 3888: invalid continuation byte
```

**Comment by kay0u** [comment]
Salut!

Visiblement tu as découvert un bug dans le core de YunoHost, [ce fix](https://github.com/YunoHost/moulinette/commit/fdc61c915ca19ad1e1a6a42cdac57c29af55eaae) devrait corriger le souci, mais il va falloir attendre la prochaine version de YunoHost (plus précisément du paquet moulinette).

Merci pour le report de bug!

**Comment by makotoworkshop** [comment]
Élo !

Nikel, l'important c'est que le soucis soit cerné, j'attendrais sagement ^^

Merci !
